# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from fractions import Fraction


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 188)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 60, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(320, 60, 71, 81))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.frac11 = QtWidgets.QSpinBox(self.centralwidget)
        self.frac11.setGeometry(QtCore.QRect(10, 60, 71, 81))
        self.frac11.setObjectName("frac11")
        self.frac12 = QtWidgets.QSpinBox(self.centralwidget)
        self.frac12.setGeometry(QtCore.QRect(80, 60, 71, 41))
        self.frac12.setObjectName("frac12")
        self.frac13 = QtWidgets.QSpinBox(self.centralwidget)
        self.frac13.setGeometry(QtCore.QRect(80, 100, 71, 41))
        self.frac13.setObjectName("frac13")
        self.frac22 = QtWidgets.QSpinBox(self.centralwidget)
        self.frac22.setGeometry(QtCore.QRect(250, 60, 71, 41))
        self.frac22.setObjectName("frac22")
        self.frac21 = QtWidgets.QSpinBox(self.centralwidget)
        self.frac21.setGeometry(QtCore.QRect(180, 60, 71, 81))
        self.frac21.setObjectName("frac21")
        self.frac23 = QtWidgets.QSpinBox(self.centralwidget)
        self.frac23.setGeometry(QtCore.QRect(250, 100, 71, 41))
        self.frac23.setObjectName("frac23")
        self.frac32 = QtWidgets.QLineEdit(self.centralwidget)
        self.frac32.setGeometry(QtCore.QRect(460, 60, 71, 41))
        self.frac32.setObjectName("frac32")
        self.frac31 = QtWidgets.QLineEdit(self.centralwidget)
        self.frac31.setGeometry(QtCore.QRect(390, 60, 71, 81))
        self.frac31.setObjectName("frac31")
        self.frac33 = QtWidgets.QLineEdit(self.centralwidget)
        self.frac33.setGeometry(QtCore.QRect(460, 100, 71, 41))
        self.frac33.setObjectName("frac33")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setMinimumSize(541, 188)
        MainWindow.setMaximumSize(541, 188)

        self.pushButton.clicked.connect(self.change)
        self.equal.clicked.connect(self.solve)


    def solve(self):
        # Перший дріб
        fraction11 = self.frac11
        fraction12 = self.frac12
        fraction13 = self.frac13

        # Другий дріб
        fraction21 = self.frac21
        fraction22 = self.frac22
        fraction23 = self.frac23

        # Третій дріб
        fraction31 = self.frac31
        fraction32 = self.frac32
        fraction33 = self.frac33

        # Перевірка дробів на правильність

        if fraction13.value() == 0:
            fraction13.setValue(1)

        if fraction23.value() == 0:
            fraction23.setValue(1)

        # Перетворення тексту

        fraction11 = fraction11.value()
        fraction12 = fraction12.value()
        fraction13 = fraction13.value()

        fraction21 = fraction21.value()
        fraction22 = fraction22.value()
        fraction23 = fraction23.value()

        # Основні дроби
        fraction1 = Fraction(fraction11 * fraction13 + fraction12, fraction13)
        fraction2 = Fraction(fraction21 * fraction23 + fraction22, fraction23)

        # Дізнаємось знак
        sign = self.pushButton.text()

        # Визначаємо результат
        if sign == "+":
            result = fraction1 + fraction2
        elif sign == "-":
            result = fraction1 - fraction2
        elif sign == "x":
            result = fraction1 * fraction2
        elif sign == ":":
            if fraction2 == 0:
                result = Fraction(1, 1)
            else:
                result = fraction1 / fraction2

        minus = str(result).startswith("-")

        # Чисельник
        numerator = result.numerator

        # Знаменник
        denominator = result.denominator

        integer = numerator // denominator

        if minus: integer = -integer

        numerator %= denominator

        if numerator == 0:
            numerator = ""
            denominator = ""
        if integer == 0: integer = ""

        fraction31.setText(str(integer))
        fraction32.setText(str(numerator))
        fraction33.setText(str(denominator))


    def change(self):
        if self.pushButton.text() == "+":
            self.pushButton.setText("-")
        elif self.pushButton.text() == "-":
            self.pushButton.setText(":")
        elif self.pushButton.text() == ":":
            self.pushButton.setText("x")
        elif self.pushButton.text() == "x":
            self.pushButton.setText("+")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор дробів"))
        self.pushButton.setText(_translate("MainWindow", "+"))
        self.equal.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
